region = "us-east-1"
instance_type = "t2.micro"
application_name = "MinhaAplicacao2"
dynamo_table_name = "app_2_user_table"
bucket_name = "app-2-bucket-tcc-unicarioca"
environment = "dev"
security_group_name = "allow_port80_application_2"
